### ISSUE TITLE
When DNS for seeds fail multidoge just hangs

### ISSUE THREAD

**Issue by kl1059** [langerhans/multidoge#40]
A popup warning for the condition would be nice.

In addition using the dogecoin core method of using a remembered list of seed IP's would also be nice.

Keeping the list of historically working seed IP's in a human readable/editable file would be even nicer!

**Comment by langerhans** [comment]
This is something that does not normally happen. It only happened here cause the only left working DNS seed was down for a while. An update for this is in the works right now.   

Since MultiDoge will be discontinued as soon as MultiDoge HD comes around I won't put much more work into the current version. Thanks for notifiying tho!
