### ISSUE TITLE
java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by mo35** [langerhans/multidoge#43]
couple weeks ago multidoge started gliching , not sure if its somehow related with latest java update or something else , but reinstalled wallets , java nothing helps , i just cannot fully sync wallet . Log goes like this , its syncs and then

09:01:20.375 [New I/O worker #31] INFO  c.g.dogecoin.core.AbstractBlockChain - 2 blocks per second 
09:01:21.619 [New I/O worker #31] INFO  c.g.dogecoin.core.AbstractBlockChain - 3 blocks per second 
09:01:22.826 [New I/O worker #31] INFO  c.g.dogecoin.core.AbstractBlockChain - 2 blocks per second 
09:01:24.785 [New I/O worker #31] INFO  c.g.dogecoin.core.AbstractBlockChain - 2 blocks per second 
09:01:25.966 [New I/O worker #31] INFO  c.g.dogecoin.core.AbstractBlockChain - 2 blocks per second 
09:01:27.846 [New I/O worker #31] INFO  c.g.dogecoin.core.AbstractBlockChain - 2 blocks per second 
09:01:29.616 [New I/O worker #31] INFO  c.g.dogecoin.core.AbstractBlockChain - 2 blocks per second 
09:02:01.808 [New I/O worker #31] WARN  com.google.dogecoin.core.Peer - [71.228.253.19]:22556 -  java.lang.OutOfMemoryError: Java heap space

09:02:03.103 [New I/O worker #31] WARN  com.google.dogecoin.core.Peer - [71.228.253.19]:22556 -  java.lang.OutOfMemoryError: Java heap space
.....
09:06:26.687 [New I/O worker #31] WARN  com.google.dogecoin.core.Peer - [71.228.253.19]:22556 -  java.lang.OutOfMemoryError: Java heap space

09:06:30.631 [New I/O worker #31] INFO  com.google.dogecoin.core.Peer - [71.228.253.19]:22556 - Incomplete packet in underlying stream 
Exception in thread "AWT-EventQueue-0" java.lang.OutOfMemoryError: Java heap space
Exception in thread "AWT-EventQueue-0" java.lang.OutOfMemoryError: Java heap space

any ideas , how to fix it , i was looking at means to pass "java -Xmx## -jar" parameter to set heap size , but unfortunatly i couldnt find jar 

using 1.6 , java 8 rel 66 on win10x64

update: if i unload wallet i can sync up to date , if im loading wallet afterwards same OOM java heap space error

update2 : i managed to find jar file in temp dir while wallet is running and copy it , after running java -Xmx2G -jar temp.jar i was able to sync wallet and make transactions normaly , so seems wallet soft dont like large wallet files , would be nice to fix it , thanks

**Comment by langerhans** [comment]
Did you read the disclaimer, when you downloaded it?  
Pretty much this is what happens if you ignore it. If you receive transactions with small outputs (and lots of them) like faucet or pool payouts, this is the inevitable results. I quote: 

>It is important to know that MultiDoge is a so called light wallet. It is meant for your day to day transactions.	If you are a miner, you should NOT use MultiDoge as your wallet. Receiving big transactions, such as pool or faucet payouts, can clog up a light wallet.	This is a known issue with all light wallets and must be considered before usage.	
The essence is: Do not use a light wallet to handle a big amount of transactions, mining being one example, faucets another. Use the reference client instead.	
The developers won't give any support in such cases and are not liable for your actions.

Your best bet is to move the wallet to a machine with lots more RAM to get it synced once and then send it to a full wallet. Otherwise, you should be able to make an unencrypted backup of the wallet in the menu, and open the file. It has all your private keys. You can then import those into dogecoin core.
