### ISSUE TITLE
MultiDoge might not work with "64-bit Java for Windows Version 8 Update 151"

### ISSUE THREAD

**Issue by praisenarsie** [langerhans/multidoge#55]
I run Windows 64-Bit.

I attempted to open MultiDoge when I was presented with this popup:
![2017-12-22_13-57-33](https://user-images.githubusercontent.com/31222036/34300538-7709ae44-e720-11e7-94f8-bf8f85d330f9.png)
I got the latest version of 64-bit Java for Windows and installed it. It still came up with the popup so I decided to install MultiDoge and yet again, still the same thing.

Any ideas? @langerhans

**Comment by langerhans** [comment]
Hm, I haven't had this issue before. But maybe I was running 32 bit Java? Can you try the solution with the JAVA_HOME variable from here? https://bitcoin.stackexchange.com/questions/24300/multibit-wont-open-says-java-not-installed

**Comment by FinkySej** [comment]
@langerhans could you please help us because we don't know what to do.. My Uncle's multidoge coin wallet is not opening.. What he did before was sync but then after he cannot open his wallet. He have multidoge application but it is not opening whenever we click it. His multidoge is 0.1.7.. 
64 bit OS x64 based processor
Windows 10
Java is jre 1.8.0_151 b12
Please help us.. He worked and pay for that dogecoins so hard.. 
Thank you

**Comment by langerhans** [comment]
Okay so first: This is not a general support forum. Second this is a whole different issue. Third, your description doesn't tell me anything about what exactly is "not opening". Did you check the thread here: https://www.reddit.com/r/multidoge/comments/29dpxk/solution_multidoge_wont_open_dont_panic/ ?

**Comment by FinkySej** [comment]
Multidoge 0.1.7 is not opening

**Comment by praisenarsie** [comment]
@langerhans That solved the issue, thanks.

**Comment by techinguy** [comment]
This website helps with setting java home variable or jre depending on what you installed, but this is true fix 

https://confluence.atlassian.com/doc/setting-the-java_home-variable-in-windows-8895.html
